#ifndef DEFINE_CONSTANTS_H
#define DEFINE_CONSTANTS_H


#define ENTRAR 0
#define VOLTAR_MENU 1

#define MENU_ALUNO 10
#define ALUNO_CADASTRAR 11
#define A_CADASTRAR 12
#define ALUNO_LISTAR 13
#define ALUNO_EDITAR 14
#define ALUNO_EXCLUIR 15
#define ALUNO_PROCURA 16
#define ALUNO_PROCURA2 17
#define ATUALIZA_ALUNO 18
#define EXCLUI_ALUNO 19
#define VOLTAR_ALUNO 20
#define VOLTAR_AL_EDITA 21
#define VOLTAR_AL_EXCLUI 22

#define MENU_PACIENTE 30
#define PACIENTE_CADASTRAR 31
#define P_CADASTRAR 32
#define PACIENTE_LISTAR 33
#define PACIENTE_EDITAR 34
#define PACIENTE_EXCLUIR 35
#define PACIENTE_PROCURA 36
#define PACIENTE_PROCURA2 37
#define ATUALIZA_PACIENTE 38
#define EXCLUI_PACIENTE 39
#define VOLTAR_PACIENTE 40
#define VOLTAR_P_EDITA 41
#define VOLTAR_P_EXCLUI 42

#define MENU_SUPERVISOR 50
#define SUPERVISOR_CADASTRAR 51
#define S_CADASTRAR 52
#define SUPERVISOR_LISTAR 53
#define SUPERVISOR_EDITAR 54
#define SUPERVISOR_EXCLUIR 55
#define SUPERVISOR_PROCURA 56
#define SUPERVISOR_PROCURA2 57
#define ATUALIZA_SUPERVISOR 58
#define EXCLUI_SUPERVISOR 59
#define VOLTAR_SUPERVISOR 60
#define VOLTAR_S_EDITA 61
#define VOLTAR_S_EXCLUI 62

#define MENU_AGENDAMENTO 70
#define AGENDAMENTO_CADASTRAR 71
#define AG_CADASTRAR 72
#define AGENDAMENTO_LISTAR 73
#define AGENDAMENTO_EXCLUIR 74
#define AGENDAMENTO_PROCURA 75
#define EXCLUI_AGENDAMENTO 76
#define VOLTAR_AGENDAMENTO 77
#define VOLTAR_AG_EXCLUI 78

#define MENU_ATENDIMENTO 80
#define ATENDIMENTO_CADASTRAR 81
#define AT_CADASTRAR 82
#define ATENDIMENTO_LISTAR 83
#define LISTAR_TODOS 84
#define LISTAR_ALUNO 85
#define LISTA_AL 86
#define LISTAR_PACIENTE 87
#define LISTA_P 88
#define LISTAR_AREA 89
#define PSICOLOGIA 90
#define ODONTOLOGIA 91
#define FISIOTERAPIA 92
#define ATENDIMENTO_EXCLUIR 93
#define ATENDIMENTO_PROCURA 94
#define EXCLUI_ATENDIMENTO 95
#define VOLTAR_ATENDIMENTO 96
#define VOLTAR_LISTA 97
#define VOLTAR_AT_EXCLUI 98


#endif
